version: "3"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - test

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "88:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - test

    rabbitmq:
        image: rabbitmq:management
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - test

networks:
    test:
        external: true
        driver: bridge
